### ISSUE TITLE
Something wrong

### ISSUE THREAD

**Issue by TobiasTe** [paul-freeman/dtw#1]
Hello,

I think there's something wrong with the implementation. I actually do not understand how you came up with this, it's just not DTW, is it?

As example consider dtw(np.array([1.,0]),np.array([0.,2.,2])).
Your implementation yields as cost matrix
(1  2  3
 1  3  5)
going down and then twice to the right. 
The correct cost matrix would be 
(1  2  3
 1  3  4)
going to the right and then diagonally down.

Best regards
Tobias

**Comment by paul-freeman** [comment]
I believe there are actually several ways to calculate a valid cost matrix (depending on how you break ties, etc.)

During the development of this algorithm, I tried to design it to agree with the [`dtw` package for R](http://dtw.r-forge.r-project.org/)

If you have cases that disagree with the reference implementation, that is certainly something I'd like to know about. In this case, however, the R implementation agrees with this package.

```R
> dtw(x=c(1.0,0.0),y=c(0.0,2.0,2.0), keep.internals=TRUE)$costMatrix
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    1    3    5
```

**Comment by TobiasTe** [comment]
Thank you for your response Paul. 
Anyway, maybe you could mention in the ReadMe that the result that your method yields are not identical to those of standard DTW as for example described on Wikipedia
https://en.wikipedia.org/wiki/Dynamic_time_warping 
or (really well explained) in section 2.1 of the following paper
https://www.cs.ucr.edu/~eamonn/KAIS_2004_warping.pdf
Kind regards
Tobias

**Comment by paul-freeman** [comment]
If you continue reading (in the paper you linked) to section 3, you will see that the cost matrix calculated depends on the step pattern used in the DTW algorithm. The algorithm I provide here intentionally uses the same step pattern as the default from the R package, a common step pattern which they call `symmetric2`. The step pattern used in the version shown on the Wikipedia page uses the equivalent of `symmetric1` from the R package.

It is probably worth knowing the step pattern being used, so I will add it to the README. Thanks for the suggestion. But I don't think it would be correct to assume there is a "standard" DTW step pattern.

**Comment by TobiasTe** [comment]
Perfect, thank you.
I guess the symmetric1 pattern is the most intuitive and basic one. Symmetric2 seems to be modified to be able to normalize the resulting distances, but seems to penalize diagonal steps? Just wondering right now, if it actually yields a positive distance when one compares two identical timeseries (say x=y=np.arange(10)). I have to try that out. Anyway, different applications have of course different requirements and different step patterns make sense, thank you for clarifying.
